# Generated by Django 4.1.2 on 2022-11-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomepg', '0002_acts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acts',
            name='act_name',
            field=models.TextField(),
        ),
    ]
