# Generated by Django 4.1.2 on 2022-11-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcomepg', '0003_alter_acts_act_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
