# Generated by Django 4.1.2 on 2022-11-15 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('welcomepg', '0005_allot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allot',
            name='auditor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='allot',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
