# Generated by Django 4.1.2 on 2022-11-16 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcomepg', '0007_remove_allot_auditor_remove_allot_contractor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allot',
        ),
        migrations.RemoveField(
            model_name='subcontractor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subcontractor',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Auditor',
        ),
        migrations.DeleteModel(
            name='Subcontractor',
        ),
    ]
